package com.mynamesraph.mystcraft.client

import com.mynamesraph.mystcraft.Mystcraft
import com.mynamesraph.mystcraft.item.MystcraftDyeing
import com.mynamesraph.mystcraft.component.PreviewTooltipComponent
import com.mynamesraph.mystcraft.registry.MystcraftItems
import net.minecraft.client.multiplayer.ClientLevel
import net.minecraft.client.renderer.block.model.ItemOverrides
import net.minecraft.client.resources.model.BakedModel
import net.minecraft.client.resources.model.ModelResourceLocation
import net.minecraft.resources.ResourceLocation
import net.minecraft.world.entity.LivingEntity
import net.minecraft.world.item.ItemStack
import net.neoforged.api.distmarker.Dist
import net.neoforged.bus.api.SubscribeEvent
import net.neoforged.fml.common.EventBusSubscriber
import net.neoforged.neoforge.client.event.ModelEvent
import net.neoforged.neoforge.client.event.RegisterColorHandlersEvent
import net.neoforged.neoforge.client.event.RegisterClientTooltipComponentFactoriesEvent
import net.neoforged.neoforge.client.model.BakedModelWrapper

/** All rendering hooks stay on the physical client. No per-color items or generated textures. */
@EventBusSubscriber(modid = Mystcraft.MOD_ID, bus = EventBusSubscriber.Bus.MOD, value = [Dist.CLIENT])
object DyedMystcraftModels {
    private val itemNames = listOf("linking_book", "book_bag")

    private fun dyedModel(name: String): ModelResourceLocation = ModelResourceLocation.standalone(
        ResourceLocation.fromNamespaceAndPath(Mystcraft.MOD_ID, "item/${name}_dyed")
    )

    @SubscribeEvent
    fun registerModels(event: ModelEvent.RegisterAdditional) {
        itemNames.forEach { event.register(dyedModel(it)) }
    }

    @SubscribeEvent
    fun wrapModels(event: ModelEvent.ModifyBakingResult) {
        // Use only this event's model map: this event can run on a resource-loading thread.
        // Do not replace the existing base JSONs (some are generated by datagen).
        for (name in itemNames) {
            val key = ModelResourceLocation(ResourceLocation.fromNamespaceAndPath(Mystcraft.MOD_ID, name), "inventory")
            val original = event.models[key] ?: continue
            val dyed = event.models[dyedModel(name)] ?: continue
            val dyeOverrides = object : ItemOverrides() {
                override fun resolve(
                    model: BakedModel, stack: ItemStack, level: ClientLevel?,
                    entity: LivingEntity?, seed: Int
                ): BakedModel? {
                    return if (MystcraftDyeing.color(stack) != null) dyed
                    else original.overrides.resolve(original, stack, level, entity, seed) ?: original
                }
            }
            event.models[key] = object : BakedModelWrapper<BakedModel>(original) {
                override fun getOverrides(): ItemOverrides = dyeOverrides
            }
        }
    }

    @SubscribeEvent
    fun registerColors(event: RegisterColorHandlersEvent.Item) {
        event.register({ stack, tintIndex ->
            // layer0 is always the untouched base; only the supplied alpha mask is dyed.
            if (tintIndex == 1) MystcraftDyeing.color(stack)?.or(-0x1000000) ?: -1 else -1
        }, MystcraftItems.LINKING_BOOK.get(), MystcraftItems.BOOK_BAG.get())
    }
    @SubscribeEvent
    fun registerTooltipComponents(event: RegisterClientTooltipComponentFactoriesEvent) {
        event.register(PreviewTooltipComponent::class.java, ::ClientPreviewTooltipComponent)
    }

}
